mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'puppetlabs/mysql'
mod 'samuelson/custom_webapp'
mod 'maestrodev-wget', '1.7.3'
